# Generated by Django 5.2.6 on 2025-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(default='Residential', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='user_id',
            field=models.IntegerField(default='Residential'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
