# Generated by Django 5.2.6 on 2025-09-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_property_id_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
