# Generated by Django 5.2.6 on 2025-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_property_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='PriceDataModel',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('area_sqft', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('property_type', models.CharField(max_length=50)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'price_data_model',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_id', models.IntegerField()),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_images',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
