# Generated by Django 5.2.6 on 2025-09-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_propertyimage_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property_id',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.property'),
        ),
    ]
