# Generated by Django 5.2.6 on 2025-09-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_property_address_property_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
