# Generated by Django 5.2.6 on 2025-09-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_estateuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estateuser',
            name='profile_photo',
        ),
    ]
