# Generated by Django 5.2.6 on 2025-09-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_estateuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
