# Generated by Django 5.2.6 on 2025-09-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_estateuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estateuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
