# Generated by Django 5.2.7 on 2025-10-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_estateuser_address_estateuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInsight',
            fields=[
                ('insight_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=50)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_change_percent', models.FloatField(default=0.0)),
                ('total_listings', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('days_on_market', models.IntegerField(default=0)),
                ('demand_score', models.FloatField(default=0.0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_insights',
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='online', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.property')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='backend.transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='backend.estateuser')),
            ],
            options={
                'db_table': 'payment_history',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(default='general', max_length=50)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='backend.estateuser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='backend.estateuser')),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_staff_response', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='backend.supportticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_responses', to='backend.estateuser')),
            ],
            options={
                'db_table': 'ticket_responses',
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('review_text', models.TextField()),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('helpful_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='backend.estateuser')),
            ],
            options={
                'db_table': 'property_reviews',
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='backend.property')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='backend.estateuser')),
            ],
            options={
                'db_table': 'saved_properties',
                'unique_together': {('user', 'property')},
            },
        ),
    ]
