# Generated by Django 5.2.6 on 2025-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_marketinsight_alter_log_action_paymenthistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=500),
        ),
    ]
