# Generated by Django 5.2.7 on 2025-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_chatbot_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to_id',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='token_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
