# Generated by Django 5.2.6 on 2025-10-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_fix_supportticket_assigned_to'),
    ]

    operations = [
    ]
